FROM debian:bookworm-slim AS build

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential libcups2-dev cups cups-filters && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY . /src
RUN make clean test && ./debian/build-deb.sh && \
    dpkg-deb --info build/tsc-da200-cups_*_*.deb && \
    dpkg-deb --contents build/tsc-da200-cups_*_*.deb && \
    dpkg -i build/tsc-da200-cups_*_*.deb && \
    test -x /usr/lib/cups/filter/rastertotspl && \
    cupstestppd -W all /usr/share/ppd/tsc/TSC-DA200.ppd

FROM scratch AS artifact
COPY --from=build /src/build/tsc-da200-cups_*_*.deb /
